gym/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings

from services.views import service_view
from home.views import home_view, about_view, work_view, contact_view, newsletter_subscribe_view, landing_page_view
from account.views import login_view, register_view
from dashboard.views import dash_view, updateuserdetails
from products.views import prod_view, order_success
from html_to_pdf.views import GeneratePdf 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('work/', work_view, name='work'),
    path('contact/', contact_view, name='contact'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('services/', service_view, name='services'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', dash_view, name='dashboard'),
    path('PCOS_Campaign/', landing_page_view, name='landing'),
    path('myorders/', dash_view, name='myorders'),
    path('product/<slug:slug>', prod_view, name='prod_detail'),
    # path('trial/<slug>', trial, name='trial'),
    path('ordersuccess', order_success, name='order_success'),
    # subscribe newsletter url
    path('subscribe-news-letter/', newsletter_subscribe_view, name='subscribe_letter'),
    # path('order_successmodal', order_successmodal, name='order_successmodal'),
    path('updateuserdetails', updateuserdetails, name='updateuserdetails'),
    url('social-auth/', include('social_django.urls', namespace='social')),
    # blog urls
    path('blog/', include('blog.urls')),
    #workout urls
    path('videos',include('workout.urls')),
    #html_top_pdf
    path('pdf/', GeneratePdf.as_view()), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.WorkoutHomeView.as_view(), name='workout_home'),
    path('post/<str:pk>/', views.WorkoutDetailView.as_view(), name='workout_detail'),
    # path('filter/', views.BlogFilterView.as_view(), name='workout_filter'),
    # path('comment/add/<str:post_id>/', views.add_comment, name='add_comment'),
]

workout/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from multiselectfield import MultiSelectField


class Workout(models.Model):
    CATEGORY = [
        ('CARDIO', 'CARDIO'),
        ('YOGA', 'YOGA'),
    ]

    video_category = models.CharField(max_length=20, choices=CATEGORY)
    video_image = models.ImageField(upload_to='workout/images')
    video_title = models.CharField(max_length=255)
    video_desc = models.TextField()
    video_link = models.URLField(max_length = 200)
    upload_datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.video_title)

    class Meta:
        db_table = 'table_videos'
        ordering = ['upload_datetime']

    # @property
    # def comment_count(self):
    #     return WorkoutComment.objects.filter(comment_blog_id=self.id).count()


# class WorkoutComment(models.Model):
#     comment_workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
#     comment_user = models.EmailField()
#     comment = models.TextField(max_length=500)
#     comment_datetime = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return str(self.comment)

#     class Meta:
#         db_table = 'table_video_comment'

workout/views.py
# from django.shortcuts import render
# from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
# from django.contrib.auth.decorators import login_required
from .models import Workout
from services.models import Service


# Create your views here.
service = Service.objects.all()

class WorkoutHomeView(ListView):
    template_name = 'workout/workout_home.html'
    paginate_by = 4
    def get_queryset(self):
        return Workout.objects.all().order_by('-pk')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkoutHomeView, self).get_context_data(**kwargs)
        context['title'] = 'Workout - GymCounselor'
        context['latest_post'] = Workout.objects.all().order_by('-pk')[:3]
        context['service'] = service
        return context


class WorkoutDetailView(DetailView):
    template_name = 'workout/workout_detail.html'

    def get_object(self, queryset=None):
        work_id = self.kwargs['pk']
        return Workout.objects.get(pk=work_id)

    def get_context_data(self, **kwargs):
        context = {
            'object': self.get_object(),
            'title': self.object.video_title,
            'latest_post': Workout.objects.all().order_by('-pk')[:3],
        }
        return context

templates/workout/workout_detail.html
{% extends 'base/base.html' %}
{% load static %}

<title>{{ title }}</title>

{% block extra_head %}
<style>
  /* .resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 56.25%;
}  

.responsive-iframe {
    align-items: center;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
} */
@media only screen and (max-width: 767px) {
    .resp-container {
    position: relative;
    overflow: hidden;
    padding-top: 56.25%;
}  

.responsive-iframe {
    align-items: center;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
}
</style>
   
{% endblock extra_head %}

{% block content %}
    
<div class="fh5co-loader"></div>

<div id="page">
    <nav class="fh5co-nav" role="navigation">
        <div class="top">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-right">
                        <ul class="fh5co-social">
                            <li><a href="https://www.instagram.com/gymcounselor/"><i class="icon-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/gymcounselor"><i class="icon-facebook"></i></a></li>
                            <li><a href="https://www.youtube.com/channel/UChvRw7rp9-gX00EpiCoMDNg"><i class="icon-youtube"></i></a></li>
                            <li><a href="https://www.linkedin.com/company/gymcounselor/"><i class="icon-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="top-menu">
            <div class="container">
                <div class="row">
                    <div class="col-xs-2">
                        <div id="fh5co-logo" style="font-family: 'Poppins', sans-serif;"><a href="{% url 'home' %}">gymCOUNSELOR<span>.</span></a></div>
                    </div>
                    <div class="col-xs-10 text-right menu-1">
                        <ul>
                            <!--<li><a href="{% url 'work' %}">Work</a></li>-->
                            <li><a href="{% url 'about' %}">About</a></li>
                            <li><a href="{% url 'contact' %}">Contact</a></li>
                            <li><a href="{% url 'blog_home' %}">Blog</a></li>

                            <li class="has-dropdown"><a>Services</a>

                                   <ul class="dropdown">
                                       {% for s in service %}
                                        <li><a href="{% url 'prod_detail' s.slug %}">{{ s.name }}</a></li>
                                        {% endfor %}

                                   </ul>
                             </li>

                            {% if request.user.is_authenticated %}
                                <li class="has-dropdown"><a> Hey, {{ user.first_name }}</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'dashboard' %}">My Profile</a></li>
                                        <li><a href="{% url 'logout' %}">Logout</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                <li class="btn-cta"><a href="{% url 'login' %}?next={{ request.path }}"><span>Login</span></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
    </header>

    <div id="fh5co-about">
        <div class="container-fluid">
            <div class="row">
                <main >
                    <div class = "resp-container" align="center">
                        <!-- <video width="320" height="240" controls>
                            <source src="{{object.video_link}}">
                        </video> -->
                        <iframe class="responsive-iframe" width="560" height="315" src="{{object.video_link}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    <br>
                    <br>
                    <br>
                    <div>
                        <h1 style="padding-bottom: 10px;  text-align: center;"><strong>{{ object.video_title|title }}</strong></h1>
                    </div>
                    <hr width="50%">
                    <div class="post-details">
                        <div class="object-meta d-flex justify-content-between" style="margin-top: 10px; text-align: center;">
                            {{ object.video_desc }}
                            <!-- <div>{{ object.blog_datetime|date:'M | Y' }}</div>
                            <div>#{{ object.blog_category }}</div> -->
                        </div>
                       
                    </div>

                    <hr width="50%">
                </main>


                
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/workout/workout_home.html
{% extends 'base/base.html' %}
{% load static %}

<title>{{ title }}</title>

{% block extra_head %}
<style>
    * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

main {
  align-items: center;
  justify-content: center;
}
.home__desc {
            font-family: 'Poppins', sans-serif !important;
            font-weight: 600 !important;
            font-size: 1.5em !important;
            margin-top: 10% !important;
}
.card {
  display: flex;
  background: linear-gradient(
    to left top,
    rgba(255, 255, 255, 0.8),
    rgba(255, 255, 255, 0.5)
  );
  border-radius: 1rem;
  margin: 2rem 0rem;
  padding: 2rem;
  box-shadow: 6px 6px 20px rgba(122, 122, 122, 0.212);
}


.card-info {
    padding: 2rem;
  display: flex;
  flex-direction: column;
}
@media only screen and (max-width: 767px) {
            .home__desc {
                font-size: 1em !important;
            }
            
            .img-responsive{
                max-height: 100px;
            }
            .card{
                max-height: 110px;
                display: flex;
                background: linear-gradient(
                    to left top,
                    rgba(255, 255, 255, 0.8),
                    rgba(255, 255, 255, 0.5)
                );
                border-radius: 1rem;
                margin: 2rem 0rem;
                padding: 1rem;
                box-shadow: 6px 6px 20px rgba(122, 122, 122, 0.212);
            }
            .card-info {
                padding: 1rem;
                display: flex;
                flex-direction: column;
            }
}
</style>
{% endblock extra_head %}

{% block content %}

    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <ul class="fh5co-social">
                                <li><a href="https://www.instagram.com/gymcounselor/"><i class="icon-instagram"></i></a></li>
                                <li><a href="https://www.facebook.com/gymcounselor"><i class="icon-facebook"></i></a></li>
                                <li><a href="https://www.youtube.com/channel/UChvRw7rp9-gX00EpiCoMDNg"><i class="icon-youtube"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/gymcounselor/"><i class="icon-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-2">
                            <div id="fh5co-logo" style="font-family: 'Poppins', sans-serif;"><a href="{% url 'home' %}">gymCOUNSELOR<span>.</span></a></div>
                        </div>
                        <div class="col-xs-10 text-right menu-1">
                            <ul>
                                <!--<li><a href="{% url 'work' %}">Work</a></li>-->
                                <li><a href="{% url 'about' %}">About</a></li>
                                <li><a href="{% url 'contact' %}">Contact</a></li>
                                <li><a href="{% url 'blog_home' %}">Blog</a></li>

                                <li class="has-dropdown"><a>Services</a>

                                       <ul class="dropdown">
                                           {% for s in service %}
                                            <li><a href="{% url 'prod_detail' s.slug %}">{{ s.name }}</a></li>
                                            {% endfor %}

                                       </ul>
                                 </li>

                                {% if request.user.is_authenticated %}
                                    <li class="has-dropdown"><a> Hey, {{ user.first_name }}</a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'dashboard' %}">My Profile</a></li>
                                            <li><a href="{% url 'logout' %}">Logout</a></li>
                                        </ul>
                                    </li>
                                {% else %}
                                    <li class="btn-cta"><a href="{% url 'login' %}?next={{ request.path }}"><span>Login</span></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </nav>

        <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
        </header>

        <div id="fh5co-about">
            <div class="container">
                    <main>
                            {% if workout_list %}
                                <div class="cards">
                                {% for post in workout_list %}
                                <a href="{% url 'workout_detail' post.id %}">
                                    <div class="card">
                                            <img class="img-responsive" src="{{ post.video_image.url }}" alt="{{ post.id }}" style="border-radius: 5px;">
                                        <div class = "card-info" >
                                            <h2 class = "home__desc" >{{ post.video_title }}</h2>
                                            <span>{{ post.upload_datetime|date:'M | Y' }} &nbsp;#{{ post.video_category }}</span> 
                                            
                                        </div>
                                               
                                    </div>
                                    </a>
                                {% endfor %}
                                </div>
                            {% else %}
                                <div style="margin-left: auto; margin-right: auto; margin-top: 200px;">
                                    <h1 class="h1" style="font-size: 6rem; font-weight: 300; line-height: 1.2;">NOT FOUND</h1>
                                </div>
                            {% endif %}
                    </main>


                    <!-- <aside class="col-lg-4">
                        <div class="d-none d-md-block" style="width: 100%;">
                            <form action="{% url 'blog_filter' %}" method="get" class="search-form">
                                <div class="d-flex">
                                    <input type="search" name="search" class="form-control" placeholder="What are you looking for?" required>
                                    <button type="submit" class="btn-danger"><i class="icon-search"></i></button>
                                </div>
                            </form>
                        </div>

                        <div class="panel panel-default" style="margin-top: 20px;">
                            <div class="panel-body">
                                <div class="panel-title">
                                    <h3 class="h3 text-center" style="margin-top: 0">Latest Posts</h3>
                                </div>
                                <div class="blog-posts">
                                    {% for post in latest_post %}
                                        <hr style="margin: 15px 0;">
                                        <a href="{% url 'blog_detail' post.id %}">
                                            <div class="item d-flex justify-content-center">
                                                <div class="image">
                                                    <img src="{{ post.blog_image.url }}" alt="{{ post.blog_title }}" width="80">
                                                </div>
                                                <div style="color:#000; margin-left: 10px;">
                                                    <p>{{ post.blog_title|title }}</p>
                                                </div>
                                            </div>
                                        </a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default" style="margin-top: 20px;">
                            <div class="panel-body">
                                <div class="panel-title">
                                    <h3 class="h3 text-center" style="margin-top: 0">Categories</h3>
                                </div>
                                <hr>
                                <div class="item d-flex justify-content-between"><a href="#">Growth</a><span>12</span></div>
                                <div class="item d-flex justify-content-between"><a href="#">Local</a><span>25</span></div>
                                <div class="item d-flex justify-content-between"><a href="#">Sales</a><span>8</span></div>
                                <div class="item d-flex justify-content-between"><a href="#">Tips</a><span>17</span></div>
                                <div class="item d-flex justify-content-between"><a href="#">Local</a><span>25</span></div>
                            </div>
                        </div>

                        <div class="panel panel-default" style="margin-top: 20px;">
                            <div class="panel-body">
                                <div class="panel-title">
                                    <h3 class="h3 text-center" style="margin-top: 0">Tags</h3>
                                </div>
                                <hr>
                                <ul class="list-inline">
                                    <li class="list-inline-item"><a href="{% url 'blog_filter' %}?tag=sport" class="tag">#SPORT</a></li>
                                    <li class="list-inline-item"><a href="{% url 'blog_filter' %}?tag=food">#FOOD</a></li>
                                    <li class="list-inline-item"><a href="{% url 'blog_filter' %}?tag=music" class="tag">#MUSIC</a></li>
                                    <li class="list-inline-item"><a href="{% url 'blog_filter' %}?tag=fitness" class="tag">#FITNESS</a></li>
                                </ul>
                            </div>
                        </div>
                    </aside> -->

                    <!-- Pagination -->
                    {% if page_obj %}
                        <div style="display:flex; width: 100%">
                            <nav style="margin: auto;" aria-label="Page navigation">
                                <ul class="pagination pagination-template">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                                    {% endif %}

                                    <li class="page-item">
                                        <span class="page-link">{{ page_obj.number }}</span>
                                    </li>


                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% endif %}
            </div>
        </div>
    </div>

{% endblock %}